### ISSUE TITLE
$ operation is invalid for atomic vectors

### ISSUE THREAD

**Issue by Goldkugel** [medizininformatik-initiative/Projectathon7-VHF#11]
Liebes Projektathon-Team,

wir konnten erfolgreich die Skripte ausführen und wären bereit die Daten auszuleiten. Allerdings, bei genauerer Betrachtung der Datei DQ-report.html, ist es möglich zu erkennen, dass ein Fehler mehrfach auftritt: "$ operator is invalid for atomic vectors". Im Anhang könnt Ihr einen Screenshot dieser Datei finden, mit den Fehlern, die ausgegeben werden. 

Könntet Ihr uns hierbei weiterhelfen? Vielen Dank dafür schon im Voraus.

Liebe Grüße

AIIM Team von der TUM

![Screenshot from 2023-03-10 11-09-24](https://user-images.githubusercontent.com/100677854/224298029-69d82a42-a571-41ef-aefb-c8ee0d273f60.png)

**Comment by astruebi** [comment]
Das DQ-Script nutzt die R-Bibliothek dataquiR. Diese ist anscheinend überhaupt nicht abwärtskompatibel. Wir haben bei der Entwicklung des DQ-Scriptes übersehen, dass wir unbedingt die dataquiR Version 1.0.9 nehmen müssen. Es ist aber momentan gegen die 2.0.0 entwickelt und wird gerade von @chhdraeger auf die 1.0.9 zurück gestellt, was das Problem beheben sollte.
Die 1.0.9 muss sein, da diese fest im aktuellen Docker-Image eingebunden ist. Das können wir aber nicht einfach mal schnell updaten, da sonst dasselbe Problem auch bei anderen von uns verwendeten R-Bibliotheken auftreten könnte. Und alles andere läuft ja mit diesem Image.
Dasselbe Problem ist für Issue #10 verantwortlich, daher ist das hier ein duplicate.
