### ISSUE TITLE
retrieve processing of Encounter failed

### ISSUE THREAD

**Issue by DWay17** [medizininformatik-initiative/Projectathon7-VHF#18]
after the Download of Encounters and Conditions the retrieve fails with an error:
```log
Patient ID Chunk Size in request: 98
Downloading Encounters and Conditions.

Error in fhir_rm_tag(x = toString(x), tag = tag) : 
  Tag closes before it opens.
Calls: append ... fhir_ns_strip -> <Anonymous> -> fhir_rm_tag -> fhir_rm_tag
Execution halted
```
the last log in fhir Server  is:
```log
2024-02-29T13:04:39.727Z 48c882c4da1b qtp1235639867-24 DEBUG [blaze.rest-api.middleware.log:14] - GET [base]/fhir/Encounter?subject=XXXX..XXX
```
and this query return an result on browser ....

**Comment by fmeineke** [comment]
Vielen Dank für das Feedback. Wir haben ein Problem mit dem Skript erkannt. Die Behebung wird heute vermutlich nicht mehr abgeschlossen / getestet werden können. Wir werden die Fristen PJT#7 verlängern lassen.
Thank you for your feedback. We have identified a problem with the script. The fix will probably not be able to be completed / tested today. We will have the deadlines PJT#7 extended.

**Comment by astruebi** [comment]
@DWay17 Ist der Fehler reproduzierbar?

**Comment by palmjulia** [comment]
@astruebi Der Fehler tritt auf, weil der fhircrackr beim Download versucht die html narrative blocks aus den Ressourcen zu löschen um Platz zu sparen. Irgendwas muss in den Ressourcen da aber Probleme machen, hatte ich noch nie. Sollte sich sofort beheben lassen, in dem man `rm_tag=NULL` setzt in allen calls von `fhir_search()`. 

Vielleicht machst du das sicherheitshalber für alle Standorte. Ich kümmere mich drum, dass ich für das Paket einen Fix schreibe, der das Problem abfängt und dann halt nicht löscht. Das kann aber ein oder zwei Wochen dauern.

**Comment by astruebi** [comment]
Erledigt wie von @palmjulia vorgeschlagen.
