### ISSUE TITLE
Ressourcen_IDs in Ergebnisse-CSVs im Projekt VHF-dezentral sind nicht pseudonymisiert 

### ISSUE THREAD

**Issue by KutSaleh** [medizininformatik-initiative/Projectathon7-VHF#4]
Die Ressourcen-IDs in den Cohort- und Diagnoses-CSVs, welche als Ergebnisse an die DMSt ausgeleitet werden sollten, sind nicht pseudonymisiert.

**Comment by astruebi** [comment]
Bei VHF-dezentral muss in der [confilg.toml](https://github.com/medizininformatik-initiative/Projectathon7-VHF/blob/b593bed32ebd027cb96888ee9c127bddbd9e1b5e/config.toml#L70) (Docker) bzw. in der [.RProfile](https://github.com/medizininformatik-initiative/Projectathon7-VHF/blob/b593bed32ebd027cb96888ee9c127bddbd9e1b5e/.RProfile#L24) (direkte Ausführung der R-Scripte) der Parameter `DECENTRAL_ANALYSIS = TRUE`sein. Das ist der Default.

Dadurch werden die CSV-Dateien vom [Retrieval](https://github.com/medizininformatik-initiative/Projectathon7-VHF/tree/master/retrieval) ins Verzeichnis `outputLocal` geschrieben. Dieses Verzeichnis wird nicht ausgeleitet. SONDERN das DIZ führt auch die [Analyse](https://github.com/medizininformatik-initiative/Projectathon7-VHF/tree/master/analysis) bei sich aus. Dabei werden die Ergebnisse ins auszuleitende Verzeichnis `outputGlobal` geschrieben. Diese Ergebnisse (PDF-Plots, Textdateien, Logs) enthalten keinerlei Resourcen_IDs. Für VHF-dezentral muss also nicht pseudonymisiert werden.
