### ISSUE TITLE
kein DQ-Report.html in outputGlobal

### ISSUE THREAD

**Issue by KutSaleh** [medizininformatik-initiative/Projectathon7-VHF#5]
Bei neuer Durchführung des Skripts (gestern pulled) fehlt das DQ-Report im Verzeichnis outputGlobal, obwohl das Sys.setenv(DATA_QUALITY_REPORT = "TRUE") eingestellt ist.

Analysis.log: 
An error occurs in Data Quality Report:
Error in system(paste(shQuote(path), "--version"), intern = TRUE): 'CreateProcess' failed to run 'Z:\pandoc.exe --version'

Hinweis: Bei alter Version  (Januar) hat es schon geklappt

**Comment by chhdraeger** [comment]
Bei mir tritt das Problem nicht auf, die Fehlermeldung deutet auf ein Problem mit der Pandoc Installation hin. Wurde seit Januar RStudio oder Pandoc nochmals installiert?

Falls Pandoc mehrfach vorkommt zeigt find_padoc() die grade geladene Version an und die anderen beiden Funktionen können zum Setzen der gewünschten Pandoc Installation genutzt werden.

`
# default pandoc version anzeigen
rmarkdown::find_pandoc()

# pandoc mit Pfad auswählen
rmarkdown::find_pandoc(cache = FALSE, dir = Sys.getenv("PANDOC_PATH"))

# pandoc nach Version auswählen
rmarkdown::find_pandoc(cache = FALSE, version = "2.7.3")
`

Eventuell hilft es auch schon die Libraries um RMarkdown zu ergänzen?
`install.packages('rmarkdown')
library(rmarkdown)`
