### ISSUE TITLE
Error in .checkTypos

### ISSUE THREAD

**Issue by DWay17** [medizininformatik-initiative/Projectathon7-VHF#7]
while executing `dupctl analyze --dup vhf` I got:
```log
Error in .checkTypos(e, names_x) : 
 Object 'clinicalStatus.code' not found amongst V1
Calls: loadAndCleanDiagnoses ... tryCatchList -> tryCatchOne -> <Anonymous> -> .checkTypos
Execution halted
```
for decentral ...

**Comment by DWay17** [comment]
@astruebi ich habe auch keine 9 Text- und 9 PDF-Dateien ...

**Comment by DWay17** [comment]
>Es werden erfolgreich 433 Observation Bundles geladen, 331 Encounter Bundles, 26 Condition Bundles. 

Es endet ohne Fehler mit 
> Extracted 4324 Encounters based on 2497 Patients.

Allerdings ist die Datei Diagnoses.csv leer.

**Comment by DWay17** [comment]
lag wohl an fehlenden Daten

**Comment by astruebi** [comment]
Sorry, ich war noch nicht soweit mir das im Detail anzusehen, aber das war auch schon meine Vermutung.
Diese Datei sollte nur leer sein, wenn gar keine Diagnosen für gefundene Patienten mit mind. einer NTproBNP-Observation auf dem Server sind. 

Hat es sich damit erledigt?

**Comment by astruebi** [comment]
Habe das Error-Logging um diesen Fall erweitert. Das Programm bricht jetzt ab, wenn es keine Conditions finden konnte, schreibt das auch in die Error-Log-Datei sowie in die Konsole und nicht die leere Tabelle Diagnoses.csv an.
